import React from 'react';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 28,
    fontFamily: 'Helvetica',
    fontSize: 10
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold'
  },
  stamp: {
    borderWidth: 1,
    borderColor: '#1f7a1f',
    color: '#1f7a1f',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 6,
    fontSize: 9,
    fontWeight: 'bold'
  },
  subtitle: {
    marginBottom: 10,
    color: '#444'
  },
  table: {
    borderWidth: 1,
    borderColor: '#202020'
  },
  row: {
    flexDirection: 'row'
  },
  headerCell: {
    backgroundColor: '#efefef',
    fontWeight: 'bold'
  },
  cell: {
    borderRightWidth: 1,
    borderRightColor: '#202020',
    borderBottomWidth: 1,
    borderBottomColor: '#202020',
    paddingVertical: 5,
    paddingHorizontal: 4,
    justifyContent: 'center'
  },
  notesCellText: {
    fontSize: 8,
    lineHeight: 1.3
  },
  footerWrap: {
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#b8b8b8',
    paddingTop: 8
  },
  footerText: {
    fontSize: 9,
    color: '#444',
    marginBottom: 12
  },
  signatureLine: {
    marginTop: 18,
    width: 220,
    borderTopWidth: 1,
    borderTopColor: '#000',
    paddingTop: 3,
    fontSize: 9
  },
  emptyMessage: {
    marginTop: 24,
    fontSize: 11,
    color: '#666',
    textAlign: 'center'
  }
});

function resolveRowsPerPage(hasDeductions) {
  return hasDeductions ? 12 : 1;
}

function chunkRows(rows, size) {
  const chunks = [];
  for (let index = 0; index < rows.length; index += size) {
    chunks.push(rows.slice(index, index + size));
  }
  return chunks.length > 0 ? chunks : [[]];
}

export default function DeductionNotesPDF({ reportData }) {
  const rows = reportData?.rows || [];
  // Filter rows that have deduction notes
  const rowsWithNotes = rows.filter(
    (row) => row.deductionNotes && row.deductionNotes.length > 0
  );

  const hasDeductions = rowsWithNotes.length > 0;
  const rowsPerPage = resolveRowsPerPage(hasDeductions);
  const pagedRows = chunkRows(rowsWithNotes, rowsPerPage);

  return (
    <Document>
      {pagedRows.map((pageRows, pageIndex) => (
        <Page key={`page-${pageIndex}`} size="A4" orientation="portrait" style={styles.page}>
          <View style={styles.headerRow}>
            <Text style={styles.title}>
              {reportData?.eventName || 'Event'} - Deduction Notes
            </Text>
            {reportData?.finalized ? (
              <Text style={styles.stamp}>FINALIZED RESULTS</Text>
            ) : null}
          </View>

          <Text style={styles.subtitle}>
            Completed Talliers: {reportData?.completedTalliers || 0}/
            {reportData?.requiredTalliers || 0}
          </Text>
          <Text style={styles.subtitle}>
            Generated By: {reportData?.generatedByName || 'Unknown User'} (
            {reportData?.generatedByRole || 'unknown'})
          </Text>

          {hasDeductions ? (
            <View style={styles.table}>
              <View style={styles.row}>
                <View
                  style={[
                    styles.cell,
                    styles.headerCell,
                    { width: '12%' }
                  ]}
                >
                  <Text>Contestant #</Text>
                </View>
                <View
                  style={[
                    styles.cell,
                    styles.headerCell,
                    { width: '20%' }
                  ]}
                >
                  <Text>Name</Text>
                </View>
                <View
                  style={[
                    styles.cell,
                    styles.headerCell,
                    { width: '12%' }
                  ]}
                >
                  <Text>Total Deductions</Text>
                </View>
                <View
                  style={[
                    styles.cell,
                    styles.headerCell,
                    { width: '56%', borderRightWidth: 0 }
                  ]}
                >
                  <Text>Deduction Details</Text>
                </View>
              </View>

              {pageRows.map((row, rowIndex) => (
                <View
                  key={row.contestantId || `${row.contestantName}-${pageIndex}-${rowIndex}`}
                  style={styles.row}
                >
                  <View style={[styles.cell, { width: '12%' }]}>
                    <Text>{row.contestantNumber ?? '-'}</Text>
                  </View>
                  <View style={[styles.cell, { width: '20%' }]}>
                    <Text>{row.contestantName}</Text>
                  </View>
                  <View style={[styles.cell, { width: '12%' }]}>
                    <Text>{row.deductionPoints ?? 0}</Text>
                  </View>
                  <View style={[styles.cell, { width: '56%', borderRightWidth: 0 }]}>
                    <Text style={styles.notesCellText}>
                      {row.deductionNotes
                        .map((entry) => `• ${entry.reason} (-${entry.deductionPoints})`)
                        .join('\n')}
                    </Text>
                  </View>
                </View>
              ))}
            </View>
          ) : (
            <Text style={styles.emptyMessage}>
              No deductions recorded for this event.
            </Text>
          )}

          <View style={styles.footerWrap}>
            <Text style={styles.footerText}>
              Downloaded on {new Date(reportData?.generatedAt || Date.now()).toLocaleString()}
            </Text>
            {hasDeductions && (
              <Text style={styles.footerText}>
                Page {pageIndex + 1} of {pagedRows.length}
              </Text>
            )}
            <Text style={styles.signatureLine}>
              Head Tabulator: {reportData?.generatedByName || '________________'}
            </Text>
          </View>
        </Page>
      ))}
    </Document>
  );
}
