import React from 'react';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 28,
    fontFamily: 'Helvetica',
    fontSize: 10
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold'
  },
  stamp: {
    borderWidth: 1,
    borderColor: '#1f7a1f',
    color: '#1f7a1f',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 6,
    fontSize: 9,
    fontWeight: 'bold'
  },
  subtitle: {
    marginBottom: 10,
    color: '#444'
  },
  table: {
    borderWidth: 1,
    borderColor: '#202020'
  },
  row: {
    flexDirection: 'row'
  },
  headerCell: {
    backgroundColor: '#efefef',
    fontWeight: 'bold'
  },
  cell: {
    borderRightWidth: 1,
    borderRightColor: '#202020',
    borderBottomWidth: 1,
    borderBottomColor: '#202020',
    paddingVertical: 5,
    paddingHorizontal: 4,
    justifyContent: 'center'
  },
  notesCellText: {
    fontSize: 7,
    lineHeight: 1.25
  },
  footerWrap: {
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#b8b8b8',
    paddingTop: 8
  },
  footerText: {
    fontSize: 9,
    color: '#444',
    marginBottom: 12
  },
  signatureLine: {
    marginTop: 18,
    width: 220,
    borderTopWidth: 1,
    borderTopColor: '#000',
    paddingTop: 3,
    fontSize: 9
  }
});

function resolveTableSizing(criteriaCount) {
  if (criteriaCount >= 12) {
    return {
      fontSize: 7,
      pageSize: 'A3',
      rankWidth: '5%',
      contestantNumberWidth: '7%',
      contestantNameWidth: '12%',
      deductionWidth: '10%',
      totalWidth: '9%',
      eventScoreWidth: '8%'
    };
  }

  if (criteriaCount >= 8) {
    return {
      fontSize: 8,
      pageSize: 'A4',
      rankWidth: '6%',
      contestantNumberWidth: '8%',
      contestantNameWidth: '14%',
      deductionWidth: '10%',
      totalWidth: '10%',
      eventScoreWidth: '8%'
    };
  }

  return {
    fontSize: 9,
    pageSize: 'A4',
    rankWidth: '8%',
    contestantNumberWidth: '10%',
    contestantNameWidth: '18%',
    deductionWidth: '10%',
    totalWidth: '12%',
    eventScoreWidth: '10%'
  };
}

function resolveRowsPerPage(criteriaCount) {
  if (criteriaCount >= 12) return 12;
  if (criteriaCount >= 8) return 14;
  return 16;
}

function chunkRows(rows, size) {
  const chunks = [];
  for (let index = 0; index < rows.length; index += size) {
    chunks.push(rows.slice(index, index + size));
  }
  return chunks.length > 0 ? chunks : [[]];
}

export default function FullResultsPDF({ reportData }) {
  const isSportsEvent = Boolean(reportData?.isSportsEvent);
  const criteria = reportData?.criteria || [];
  const rows = reportData?.rows || [];
  const completedJudges = Number(reportData?.completedJudges ?? reportData?.completedTalliers ?? 0);
  const requiredJudges = Number(reportData?.requiredJudges ?? reportData?.requiredTalliers ?? 0);

  if (isSportsEvent) {
    const rankingScale = reportData?.rankingScale || { 1: 10, 2: 7, 3: 5, 4: 3, 5: 2, 6: 1, 7: 0 };

    return (
      <Document>
        <Page size="A4" orientation="landscape" style={styles.page}>
          <View style={styles.headerRow}>
            <Text style={styles.title}>{reportData?.eventName || 'Event'} - Master Results</Text>
            {reportData?.finalized ? <Text style={styles.stamp}>FINALIZED RESULTS</Text> : null}
          </View>

          <Text style={styles.subtitle}>
            Generated By: {reportData?.generatedByName || 'Unknown User'} ({reportData?.generatedByRole || 'unknown'})
          </Text>
          <Text style={styles.subtitle}>Ranking scale: 1=10, 2=7, 3=5, 4=3, 5=2, 6=1, 7=0</Text>

          <View style={styles.table}>
            <View style={styles.row}>
              <View style={[styles.cell, styles.headerCell, { width: '12%' }]}>
                <Text>Rank</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: '18%' }]}>
                <Text>Contestant #</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: '40%' }]}>
                <Text>Contestant</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: '10%' }]}>
                <Text>Win</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: '10%' }]}>
                <Text>Loss</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: '10%', borderRightWidth: 0 }]}>
                <Text>Event Score</Text>
              </View>
            </View>

            {rows.map((row, index) => {
              const rankingPoints = Number(row.rankingPoints ?? rankingScale[row.rank] ?? 0);

              return (
                <View key={row.contestantId || `${row.contestantName}-${index}`} style={styles.row}>
                  <View style={[styles.cell, { width: '12%' }]}>
                    <Text>{row.rank ?? index + 1}</Text>
                  </View>
                  <View style={[styles.cell, { width: '18%' }]}>
                    <Text>{row.contestantNumber ?? '-'}</Text>
                  </View>
                  <View style={[styles.cell, { width: '40%' }]}>
                    <Text>{row.contestantName}</Text>
                  </View>
                  <View style={[styles.cell, { width: '10%' }]}>
                    <Text>{row.wins ?? 0}</Text>
                  </View>
                  <View style={[styles.cell, { width: '10%' }]}>
                    <Text>{row.losses ?? 0}</Text>
                  </View>
                  <View style={[styles.cell, { width: '10%', borderRightWidth: 0 }]}>
                    <Text>{Number(rankingPoints || 0).toFixed(0)}</Text>
                  </View>
                </View>
              );
            })}
          </View>

          <View style={styles.footerWrap}>
            <Text style={styles.footerText}>Downloaded on {new Date(reportData?.generatedAt || Date.now()).toLocaleString()}</Text>
            <Text style={styles.footerText}>Page 1 of 1</Text>
            <Text style={styles.signatureLine}>Head Tabulator: {reportData?.generatedByName || '________________'}</Text>
          </View>
        </Page>
      </Document>
    );
  }

  const sizing = resolveTableSizing(criteria.length);
  const rankWidth = Number((sizing.rankWidth || '0%').replace('%', ''));
  const contestantNumberWidth = Number(sizing.contestantNumberWidth.replace('%', ''));
  const contestantNameWidth = Number(sizing.contestantNameWidth.replace('%', ''));
  const deductionWidth = Number(sizing.deductionWidth.replace('%', ''));
  const totalWidth = Number(sizing.totalWidth.replace('%', ''));
  const eventScoreWidth = Number((sizing.eventScoreWidth || '0%').replace('%', ''));
  const remainingWidth = Math.max(0, 100 - rankWidth - contestantNumberWidth - contestantNameWidth - deductionWidth - totalWidth - eventScoreWidth);
  const criteriaWidth = criteria.length > 0 ? `${remainingWidth / criteria.length}%` : '0%';
  const rowsPerPage = resolveRowsPerPage(criteria.length);
  const pagedRows = chunkRows(rows, rowsPerPage);

  return (
    <Document>
      {pagedRows.map((pageRows, pageIndex) => (
        <Page key={`page-${pageIndex}`} size={sizing.pageSize} orientation="landscape" style={[styles.page, { fontSize: sizing.fontSize }]}>
          <View style={styles.headerRow}>
            <Text style={styles.title}>{reportData?.eventName || 'Event'} - Master Results</Text>
            {reportData?.finalized ? <Text style={styles.stamp}>FINALIZED RESULTS</Text> : null}
          </View>

          <Text style={styles.subtitle}>
            Completed Judges: {completedJudges}/{requiredJudges}
          </Text>
          <Text style={styles.subtitle}>
            Generated By: {reportData?.generatedByName || 'Unknown User'} ({reportData?.generatedByRole || 'unknown'})
          </Text>

          <View style={styles.table}>
            <View style={styles.row}>
              <View style={[styles.cell, styles.headerCell, { width: sizing.rankWidth }]}>
                <Text>Rank</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: sizing.contestantNumberWidth }]}>
                <Text>Contestant #</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: sizing.contestantNameWidth }]}>
                <Text>Contestant</Text>
              </View>
              {criteria.map((criterion) => (
                <View key={`header-${pageIndex}-${criterion}`} style={[styles.cell, styles.headerCell, { width: criteriaWidth }]}>
                  <Text>{criterion}</Text>
                </View>
              ))}
              <View style={[styles.cell, styles.headerCell, { width: sizing.deductionWidth }]}>
                <Text>Deductions</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: sizing.totalWidth }]}>
                <Text>Total Score</Text>
              </View>
              <View style={[styles.cell, styles.headerCell, { width: sizing.eventScoreWidth || '10%', borderRightWidth: 0 }]}>
                <Text>Event Score</Text>
              </View>
            </View>

            {pageRows.map((row, rowIndex) => (
              <View key={row.contestantId || `${row.contestantName}-${pageIndex}-${rowIndex}`} style={styles.row}>
                <View style={[styles.cell, { width: sizing.rankWidth }]}>
                  <Text>{row.rank ?? pageIndex * rowsPerPage + rowIndex + 1}</Text>
                </View>
                <View style={[styles.cell, { width: sizing.contestantNumberWidth }]}>
                  <Text>{row.contestantNumber ?? '-'}</Text>
                </View>
                <View style={[styles.cell, { width: sizing.contestantNameWidth }]}>
                  <Text>{row.contestantName}</Text>
                </View>
                {criteria.map((criterion) => (
                  <View key={`${row.contestantId || rowIndex}-${pageIndex}-${criterion}`} style={[styles.cell, { width: criteriaWidth }]}>
                    <Text>{row.criterionScores?.[criterion] ?? '-'}</Text>
                  </View>
                ))}
                <View style={[styles.cell, { width: sizing.deductionWidth }]}>
                  <Text>{row.deductionPoints ?? 0}</Text>
                </View>
                <View style={[styles.cell, { width: sizing.totalWidth }]}>
                  <Text>{row.totalScore ?? '-'}</Text>
                </View>
                <View style={[styles.cell, { width: sizing.eventScoreWidth || '10%', borderRightWidth: 0 }]}>
                  <Text>{row.eventScore ?? '-'}</Text>
                </View>
              </View>
            ))}
          </View>

          <View style={styles.footerWrap}>
            <Text style={styles.footerText}>Downloaded on {new Date(reportData?.generatedAt || Date.now()).toLocaleString()}</Text>
            <Text style={styles.footerText}>Page {pageIndex + 1} of {pagedRows.length}</Text>
            <Text style={styles.signatureLine}>Head Tabulator: {reportData?.generatedByName || '________________'}</Text>
          </View>
        </Page>
      ))}
    </Document>
  );
}
