import React from 'react';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 28,
    fontFamily: 'Helvetica',
    fontSize: 10
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold'
  },
  stamp: {
    borderWidth: 1,
    borderColor: '#1f7a1f',
    color: '#1f7a1f',
    borderRadius: 4,
    paddingVertical: 3,
    paddingHorizontal: 6,
    fontSize: 9,
    fontWeight: 'bold'
  },
  subtitle: {
    marginBottom: 10,
    color: '#444'
  },
  table: {
    borderWidth: 1,
    borderColor: '#202020'
  },
  row: {
    flexDirection: 'row'
  },
  headerCell: {
    backgroundColor: '#efefef',
    fontWeight: 'bold'
  },
  cell: {
    borderRightWidth: 1,
    borderRightColor: '#202020',
    borderBottomWidth: 1,
    borderBottomColor: '#202020',
    paddingVertical: 5,
    paddingHorizontal: 4,
    justifyContent: 'center'
  },
  footerWrap: {
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#b8b8b8',
    paddingTop: 8
  },
  footerText: {
    fontSize: 9,
    color: '#444',
    marginBottom: 12
  },
  signatureLine: {
    marginTop: 18,
    width: 220,
    borderTopWidth: 1,
    borderTopColor: '#000',
    paddingTop: 3,
    fontSize: 9
  }
});

export default function TabulationReportPDF({ reportData }) {
  const rows = reportData?.rows || [];
  const currentJudges = Number(reportData?.currentJudges ?? reportData?.currentTallies ?? 0);
  const requiredJudges = Number(reportData?.requiredJudges ?? reportData?.requiredTalliers ?? 0);

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.headerRow}>
          <Text style={styles.title}>{reportData?.eventName || 'Event'} - Tabulation Report</Text>
          {reportData?.finalized ? <Text style={styles.stamp}>FINALIZED RESULTS</Text> : null}
        </View>

        <Text style={styles.subtitle}>Status: {currentJudges}/{requiredJudges} Judges Submitted</Text>
        <Text style={styles.subtitle}>Generated By: {reportData?.generatedByName || 'Unknown User'} (tabulator)</Text>

        <View style={styles.table}>
          <View style={styles.row}>
            <View style={[styles.cell, styles.headerCell, { width: '10%' }]}>
              <Text>Rank</Text>
            </View>
            <View style={[styles.cell, styles.headerCell, { width: '38%' }]}>
              <Text>Contestant</Text>
            </View>
            <View style={[styles.cell, styles.headerCell, { width: '18%' }]}>
              <Text>Average Score</Text>
            </View>
            <View style={[styles.cell, styles.headerCell, { width: '18%' }]}>
              <Text>Final Score</Text>
            </View>
          </View>

          {rows.map((row, index) => (
            <View key={row.contestantId || `${row.contestantName}-${index}`} style={styles.row}>
              <View style={[styles.cell, { width: '10%' }]}>
                <Text>{index + 1}</Text>
              </View>
              <View style={[styles.cell, { width: '38%' }]}>
                <Text>{row.contestantName}</Text>
              </View>
              <View style={[styles.cell, { width: '18%' }]}>
                <Text>{row.averageScore ?? '-'}</Text>
              </View>
              <View style={[styles.cell, { width: '18%' }]}>
                <Text>{row.finalScore ?? row.averageScore ?? '-'}</Text>
              </View>
            </View>
          ))}
        </View>

        <View style={styles.footerWrap}>
          <Text style={styles.footerText}>Downloaded on {new Date(reportData?.generatedAt || Date.now()).toLocaleString()}</Text>
          <Text style={styles.footerText}>Page 1 of 1</Text>
          <Text style={styles.signatureLine}>Head Tabulator: {reportData?.generatedByName || '________________'}</Text>
        </View>
      </Page>
    </Document>
  );
}
