import React from 'react';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 28,
    fontFamily: 'Helvetica',
    fontSize: 10
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 6
  },
  subtitle: {
    marginBottom: 8,
    color: '#444'
  },
  table: {
    borderWidth: 1,
    borderColor: '#202020',
    marginTop: 8
  },
  row: {
    flexDirection: 'row'
  },
  headerCell: {
    backgroundColor: '#efefef',
    fontWeight: 'bold'
  },
  cell: {
    borderRightWidth: 1,
    borderRightColor: '#202020',
    borderBottomWidth: 1,
    borderBottomColor: '#202020',
    paddingVertical: 5,
    paddingHorizontal: 4,
    justifyContent: 'center'
  },
  footerWrap: {
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: '#b8b8b8',
    paddingTop: 8
  },
  footerText: {
    fontSize: 9,
    color: '#444',
    marginBottom: 8
  }
});

export default function WeightedRankingsPDF({ reportData }) {
  const rows = reportData?.weightedRankings || [];
  const weightedPointsByRank = reportData?.weightedPointsByRank || {};
  const weightingLabel = Object.keys(weightedPointsByRank)
    .sort((a, b) => Number(a) - Number(b))
    .map((rank) => `${rank}=${weightedPointsByRank[rank]}`)
    .join(', ');

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <Text style={styles.title}>Overall Weighted Rankings</Text>
        <Text style={styles.subtitle}>Weighting scale: {weightingLabel}</Text>
        <Text style={styles.subtitle}>Generated By: {reportData?.generatedByName || 'Unknown User'}</Text>

        <View style={styles.table}>
          <View style={styles.row}>
            <View style={[styles.cell, styles.headerCell, { width: '10%' }]}>
              <Text>Rank</Text>
            </View>
            <View style={[styles.cell, styles.headerCell, { width: '26%' }]}>
              <Text>Contender</Text>
            </View>
            <View style={[styles.cell, styles.headerCell, { width: '14%' }]}>
              <Text>Weighted Points</Text>
            </View>
            <View style={[styles.cell, styles.headerCell, { width: '50%', borderRightWidth: 0 }]}>
              <Text>Breakdown (Event: Rank to Points)</Text>
            </View>
          </View>

          {rows.map((row, index) => {
            const breakdown = (row.eventBreakdown || [])
              .map((entry) => `${entry.eventName}: #${entry.eventRank} -> ${entry.weightedPoints}`)
              .join(' | ');

            return (
              <View key={`${row.contestantName}-${index}`} style={styles.row}>
                <View style={[styles.cell, { width: '10%' }]}>
                  <Text>{row.rank}</Text>
                </View>
                <View style={[styles.cell, { width: '26%' }]}>
                  <Text>{row.contestantName}</Text>
                </View>
                <View style={[styles.cell, { width: '14%' }]}>
                  <Text>{Number(row.weightedTotal || 0).toFixed(2)}</Text>
                </View>
                <View style={[styles.cell, { width: '50%', borderRightWidth: 0 }]}>
                  <Text>{breakdown || '-'}</Text>
                </View>
              </View>
            );
          })}
        </View>

        <View style={styles.footerWrap}>
          <Text style={styles.footerText}>Downloaded on {new Date(reportData?.generatedAt || Date.now()).toLocaleString()}</Text>
        </View>
      </Page>
    </Document>
  );
}
